(define (frame-border->painter)
    (lambda (frame)
      (let ((segment1 (make-segment (origin-frame frame) (add-vector (origin-frame frame) (edage1-frame frame))))
            (segment2 (make-segment (origin-frame frame) (add-vertor (origin-frame frame) (edage2-frame frame))))
            (segment3 (make-segment (add-vertor (origin-frame frame) (edage1-frame frame)) (add-vertor (origin-frame frame) (add-vertor (edage1-frame frame) (edage2-frame frame)))))
            (segment4 (make-segment (add-vertor (origin-frame frame) (edage2-frame frame)) (add-vertor (origin-frame frame) (add-vertor (edage1-frame frame) (edage2-frame frame)))))
            )
      (segments-origin->painter (list segment1 segment2 segment3 segment4)))))

(define (diagonal->painter)
    (lambda (frame)
      (let ((diagonal1 (make-segment (origin-frame frame) (add-vector (origin-frame frame) (add-vertor (edage1-frame frame) (edage2-frame frame)))))
            (diagonal2 (make-segment (add-vertor (origin-frame frame) (edage1-frame frame)) (add-vertor (origin-frame frame) (edage2-frame frame))))
            )
      (segments-origin->painter (list diagonal1 diagonal2)))))

(define (middle-frame->painter)
    (lambda (frame)
      (let ((segment1 (make-segment (origin-frame frame) (scale-vect 0.5 (add-vector (origin-frame frame) (edage1-frame frame)))))
            (segment2 (make-segment (origin-frame frame) (scale-vect 0.5(add-vertor (origin-frame frame) (edage2-frame frame)))))
            (segment3 (make-segment (add-vertor (origin-frame frame) (edage1-frame frame)) (scale-vect 0.5 (add-vertor (origin-frame frame) (add-vertor (edage1-frame frame) (edage2-frame frame))))))
            (segment4 (make-segment (add-vertor (origin-frame frame) (edage2-frame frame)) (scale-vect 0.5 (add-vertor (origin-frame frame) (add-vertor (edage1-frame frame) (edage2-frame frame))))))
            )
      (segments-origin->painter (list segment1 segment2 segment3 segment4)))))
;; previous is wrong please look at https://wizardbook.wordpress.com/2010/12/03/exercise-2-49/

(define wave-painter-segments
  (list
   (make-segment (make-vert 0.2 0.0) (make-vertor 0.4 0.4))
   (make-segment (make-vect 0.4 0.4) (make-vect 0.3 0.5))
   (make-segment (make-vect 0.3 0.5) (make-vect 0.1 0.3))
   (make-segment (make-vect 0.1 0.3) (make-vect 0.0 0.6))
   (make-segment (make-vect 0.0 0.8) (make-vect 0.1 0.5))
   (make-segment (make-vect 0.1 0.5) (make-vect 0.3 0.6))
   (make-segment (make-vect 0.3 0.6) (make-vect 0.4 0.6))
   (make-segment (make-vect 0.4 0.6) (make-vect 0.3 0.8))
   (make-segment (make-vect 0.3 0.8) (make-vect 0.4 1.0))
   (make-segment (make-vect 0.6 1.0) (make-vect 0.7 0.8))
   (make-segment (make-vect 0.7 0.8) (make-vect 0.6 0.6))
   (make-segment (make-vect 0.6 0.6) (make-vect 0.8 0.6))
   (make-segment (make-vect 0.8 0.6) (make-vect 1.0 0.4))
   (make-segment (make-vect 1.0 0.2) (make-vect 0.6 0.4))
   (make-segment (make-vect 0.6 0.4) (make-vect 0.8 0.0))
   (make-segment (make-vect 0.7 0.0) (make-vect 0.5 0.3))
   (make-segment (make-vect 0.5 0.3) (make-vect 0.3 0.0))
   ))

(define wave (segments->painter wave-painter-segments))
