(define (make-accout balance password)
  (define (wiathdraw amount)
    (if (>= blance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch key m)
    (cond ((not (eq? key password))
           (error "Incorrect passwor -- MARK_ACCOUNT"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unkown request -- MQRK_ACCOUNT" m))))
  dispatch)
